services:
  - type: web
    name: familytree-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    branch: main
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk
